version: "3.8"

services:
  postgres-db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spring-net

  spring-app:
    image: spring-app
    container_name: spring-app
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    volumes:
      - shared-data:/app/shared
    networks:
      - spring-net
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - shared-data:/app/shared
      - shared-data:/var/lib/rabbitmq
    networks:
      - spring-net
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  python-worker:
    image: worker-image
    container_name: python-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
    volumes:
      - shared-data:/app/shared
    networks:
      - spring-net

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins_container
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - shared-data:/app/shared
    networks:
      - spring-net

networks:
  spring-net:

volumes:
  pgdata:
    external: true
  shared-data:
    external: true
